wheel-factory:
  image: zapgo/wheel-factory
  build:
    context: ./factory
    dockerfile: Dockerfile
  volumes:
    - /srv/build/wheelhouse:/wheelhouse
    - /srv/build/archive:/archive
    - /srv/build/requirements.txt:/app/requirements.txt
  environment:
    - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
    - WHEELHOUSE=/wheelhouse
    - PIP_WHEEL_DIR=/wheelhouse
    - PIP_FIND_LINKS=/archive
    - VIRTUAL_ENV=/env
    - CEXT=True
